### ISSUE TITLE
Grafana dashboards

### ISSUE THREAD

**Issue by proffust** [openiomon/hds2graphite#1]
Hello!
Please share grafana dashboards for realtime metrics.

**Comment by munokar** [comment]
Hello!
I have uploaded some example dashboards.
Some of them are based on the realtime data.

Regards
Muno

**Comment by munokar** [comment]
The dashboards are currently not in the RPM package / release.

**Comment by proffust** [comment]
Hello!
I cannot import dashboards, after import empty screen. I tried on versions 4.6.5, 5.4.5 and 6.6.2

**Comment by munokar** [comment]
Hi,
how have you tried to do the import?
Via Scipt or UI?
Regards
Muno

**Comment by proffust** [comment]
Via UI, PLUS buton, import, upload JSON

**Comment by munokar** [comment]
Hi,

the JSON files are for import via CLI.
If you want to import them via UI you have to remove some lines from the files in the beginning of each file:

{
    "meta": {
        "type": "db",
        "canSave": true,
        "canEdit": true,
        "canAdmin": false,
        "canStar": true,
        "slug": "hds-cache-details",
        "url": "/d/3DVt_Yezz/hds-cache-details",
        "expires": "0001-01-01T00:00:00Z",
        "created": "2018-05-14T09:12:00+02:00",
        "updated": "2018-12-06T14:19:16+01:00",
        "updatedBy": "munokar",
        "createdBy": "Anonymous",
        "version": 8,
        "hasAcl": false,
        "isFolder": false,
        "folderId": 176,
        "folderTitle": "HDS",
        "folderUrl": "/dashboards/f/qOOUz2pik/hds",
        "provisioned": false,
        "provisionedExternalId": ""
    },
    "dashboard": 

and some line in the end

,
    "overwrite": true
}

So only the contect of the XML Element Dashboads stays in the file / XML code.

Regards
Muno

**Comment by proffust** [comment]
It's works! Thanks
