### ISSUE TITLE
Systemd-Daemon-0.05/06/07 install fail 

### ISSUE THREAD

**Issue by vcfff** [openiomon/hds2graphite#3]
```
[root@rhel Systemd-Daemon-0.05]# cd ../Systemd-Daemon-0.06/
[root@rhel Systemd-Daemon-0.06]# perl Makefile.PL
Generating a Unix-style Makefile
Writing Makefile for Systemd::Daemon
Writing MYMETA.yml and MYMETA.json
[root@rhel Systemd-Daemon-0.06]# make
Skip blib/lib/Systemd/Daemon/Inline.pm (unchanged)
Skip blib/lib/Systemd/Daemon.pm (unchanged)
"/usr/bin/perl" "-Iblib/arch" "-Iblib/lib" Makefile.PL MANIFEST.SKIP
"/usr/bin/perl" "-Iblib/arch" "-Iblib/lib" Makefile.PL rpm/perl-Systemd-Daemon.spec
Manifying 1 pod document
[root@rhel Systemd-Daemon-0.06]# make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ............ 1/? # Testing Systemd::Daemon 0.06, Perl 5.016003, /usr/bin/perl
t/00-load.t ............ ok
t/01-notify.t .......... XDG_RUNTIME_DIR is not defined
# Looks like your test exited with 255 before it could output anything.
t/01-notify.t .......... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 9/9 subtests
t/91-cpan-meta.t ....... skipped: Author tests not required for installation
t/92-cpan-meta-yml.t ... skipped: Author tests not required for installation
t/93-cpan-meta-json.t .. skipped: Author tests not required for installation
t/94-manifest.t ........ skipped: Author tests not required for installation
t/95-pod.t ............. skipped: Author tests not required for installation
t/96-pod-coverage.t .... skipped: Author tests not required for installation

Test Summary Report
-------------------
t/01-notify.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 9 tests but ran 0.
Files=8, Tests=1,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.39 cusr  0.07 csys =  0.50 CPU)
Result: FAIL
Failed 1/8 test programs. 0/1 subtests failed.
make: *** [test_dynamic] Error 255
-----
```
Hi i am unable to install any of "Systemd::Daemon" on 
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
any idea with this?

**Comment by mamoep** [comment]
You don't need to install it seperatly, it is included in the rpm. https://github.com/openiomon/hds2graphite/releases/tag/v0.3.4

**Comment by vcfff** [comment]
my bad, i not read it well, installation instruction, may you please advice which other packages and versions to install for this remaining parts?
![image](https://user-images.githubusercontent.com/34322438/89231612-f56cd980-d5e5-11ea-91a0-dca72df7f2fe.png)

**Comment by mamoep** [comment]
go-carbon and graphite-api are our standard environment. Go-carbon RPMs are available on GitHub, graphite-api RPMs are in epel repo as far as I remember. Use latest versions.

**Comment by Trolls** [comment]
Hello,

Many thanks for this tools.

I got the same problem on a CentOS Linux release 7.8.2003 (Core)

I can't install the  Systemd/Daemon.pm  =which need with the rpm  hds2graphite-0.3-4.x86_64.rpm

[root@vm-grafana tmp]# rpm -Uvh hds2graphite-0.3-4.x86_64.rpm
Preparing...                          ################################# [100%]
        package hds2graphite-0.3-4.x86_64 is already installed

[root@vm-grafana tmp]# /usr/bin/perl /opt/hds2graphite/bin/hds2graphite-worker.pl -conf /opt/hds2graphite/conf/hds2graphite.conf -storagesystem 11128 -hours 1 -daemon
Can't locate Systemd/Daemon.pm in @INC (@INC contains: /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/hds2graphite/bin/hds2graphite-worker.pl line 30.
BEGIN failed--compilation aborted at /opt/hds2graphite/bin/hds2graphite-worker.pl line 30.

So i tried to install with with  CPAN:

[root@vm-grafana hds2graphite]# cpan Systemd::Daemon
CPAN: Storable loaded ok (v2.45)
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 09 Oct 2020 02:17:03 GMT
Running install for module 'Systemd::Daemon'
Running make for V/VD/VDB/Systemd-Daemon-0.07.tar.gz
CPAN: Digest::SHA loaded ok (v5.85)
CPAN: Compress::Zlib loaded ok (v2.061)
Checksum for /root/.cpan/sources/authors/id/V/VD/VDB/Systemd-Daemon-0.07.tar.gz ok
CPAN: File::Temp loaded ok (v0.2301)
CPAN: Parse::CPAN::Meta loaded ok (v1.4404)
CPAN: CPAN::Meta loaded ok (v2.120921)
CPAN: Module::CoreList loaded ok (v2.76_02)

  CPAN.pm: Building V/VD/VDB/Systemd-Daemon-0.07.tar.gz

Can't link/include C library 'systemd', aborting.
No 'Makefile' createdCPAN: YAML loaded ok (v0.84)
  VDB/Systemd-Daemon-0.07.tar.gz
  /usr/bin/perl Makefile.PL -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
[root@vm-grafana hds2graphite]#


Many thanks for help.

Br,

**Comment by mamoep** [comment]
As stated before, the module is included in the rpm. The way it is linked you can‘t call the worker directly without adding the lib subdirectory to your Perl path. Just call the hds2graphite.pl to start it.

**Comment by Trolls** [comment]
it's ok many thanks :perl -i /opt/hds2graphite/lib/perl5/ /opt/hds2graphite/bin/hds2graphite -conf /opt/hds2graphite/conf/hds2graphite.conf -storagesystem 11128


I have an another question please, it is possible to import/copy the the final output "the out directory" directly in this tools without use the local collect process ?

in fact bypass this process:
2020/10/09 10:00:03 [INFO] (/opt/hds2graphite/bin/hds2graphite-worker.pl:1092) main::raidcomlogin > Logging in with raidcom on instance #11 with user CCI_USERNAME
2020/10/09 10:00:05 [DEBUG] (/opt/hds2graphite/bin/hds2graphite-worker.pl:1054) main::execccicmd > CCI Command Fork for command /opt/hds2graphite/cci/HORCM/usr/bin/raidcom -login CCI_USERNAME CCI_PASSWORD -I11 with PID 32116 ended successful with returncode 255


Many thanks,

Br,

**Comment by mamoep** [comment]
Sorry I don‘t understand what you are trying to achieve. The CCI login is to get configuration information from the storage system. The information is held in memory.

**Comment by Trolls** [comment]
i would like to use this tool in offline mode, without connexion with any SVP.
It's possible to import configuration and export tool result data from outside?

**Comment by munokar** [comment]
Hi, since the export tool is missing some information (e.g. pool data) it is necessary to have a connection to the SVP via IP or  a FC command device to use RAIDCOM to query LDEV, Pool, HSD infos etc...
So using it "Offline" is currently not possible.

**Comment by Trolls** [comment]
yes of course i understand
But perhaps, it's possible to import these raidcom commands in a folder?

i'm not a big devlope in perl, but maybe i will try to develop this offline mode if you are ok? but i need litlle bit your help :)

**Comment by munokar** [comment]
It would be necessary to write some sort of RAIDCOM emulator that reads the output of the original RAIDCOM command and return this to hds2graphite...

**Comment by mamoep** [comment]
information provided
