### ISSUE TITLE
Json files

### ISSUE THREAD

**Issue by kimuraal** [openiomon/hds2graphite#6]
I tried importing the json files but the graphics don't show up. Has anyone had this problem ?

**Comment by mamoep** [comment]
Were you talking about the Dashboard import into Grafana? Missing metrics are most likely related to using the wrong datasource or not having any data source configured. Do you still require assistance?

**Comment by Trolls** [comment]
hello, 

- You have to import the grafana key on "/root/.grafanakey # if you use root user

- From sources, import dashboard json files:

[root@vm-grafana-6 bin]# pwd
/tmp/hds2graphite-master/bin
./import_grafana_db.sh http://x.x.x.x:3000 ../dashboards/
