### ISSUE TITLE
checkreporter error

### ISSUE THREAD

**Issue by tim-99** [openiomon/hds2graphite#8]
Hi,
we got the following error, any ideas?

[ERROR] (/opt/hds2graphite/bin/[hds2graphite-realtime.pl:580](http://hds2graphite-realtime.pl:580/)) main::checkreporter > Looks like PID: 35595 for unit RAID_PI_RGS is not running! It ended with returncode 111

ERROR] (/opt/hds2graphite/bin/[hds2graphite-realtime.pl:581](http://hds2graphite-realtime.pl:581/)) main::checkreporter > Restarting for Unit: RAID_PI_RGS

**Comment by munokar** [comment]
Hi,
can you provide some additional log infos.
Are are there any other messages in the log?
In many cases the child process dies because it gets an invalid response via HTTP vom the HTNM / HIAA / Analyzer-Server.
In this case you should see some lines before the message something like:

````
2022/07/15 04:00:12 [ERROR] (/opt/hds2graphite/bin/hds2graphite-realtime.pl:309) main::http_get > Failed to GET data from https://myserver.local:22016/Analytics/RAIDAgent/v1/objects/RAID_PI
_CHS?hostName=myagenet.local&agentInstanceName=G1500_12345 with HTTP GET error code: 503
````

**Comment by mamoep** [comment]
New release v0.4.0 should write to log file why the process died.
